#!/bin/bash
# Quick Start Guide - Knowledge Battle Authentication

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  KNOWLEDGE BATTLE - EMAIL OTP AUTHENTICATION SYSTEM        ║"
echo "║  Status: READY FOR CONFIGURATION                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 SYSTEM CHECKLIST${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅${NC} Modern UI/UX Design (Glassmorphism)"
echo -e "${GREEN}✅${NC} 3-Step Registration with Email OTP"
echo -e "${GREEN}✅${NC} Login with Rate Limiting"
echo -e "${GREEN}✅${NC} BCRYPT Password Hashing"
echo -e "${GREEN}✅${NC} Form Validation (Client + Server)"
echo -e "${GREEN}✅${NC} Responsive Design (Mobile, Tablet, Desktop)"
echo -e "${GREEN}✅${NC} Security Best Practices"
echo -e "${GREEN}✅${NC} Complete Documentation"
echo ""

echo -e "${YELLOW}⚠️  REQUIRED CONFIGURATION${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${RED}❌${NC} Email Credentials (5 min setup)"
echo ""

echo -e "${BLUE}🚀 QUICK START (3 STEPS)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 1: Enable Gmail 2FA (if using Gmail)"
echo "  • Go to: https://myaccount.google.com"
echo "  • Click: Security (Keamanan)"
echo "  • Enable: 2-Step Verification"
echo "  • Time: ~2 minutes"
echo ""
echo "STEP 2: Get App Password"
echo "  • Go to: https://myaccount.google.com/apppasswords"
echo "  • App: Mail | Device: Windows Computer"
echo "  • Copy: 16-character password"
echo "  • Time: ~1 minute"
echo ""
echo "STEP 3: Configure Email File"
echo "  • Open: /service/config.email.php"
echo "  • Edit:"
echo "    - 'username' → your-email@gmail.com"
echo "    - 'password' → your-16-char-password"
echo "    - 'email' → your-email@gmail.com"
echo "  • Save file"
echo "  • Time: ~2 minutes"
echo ""

echo -e "${BLUE}✨ TESTING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION A: Test Without Email (Development)"
echo "  • Leave config.email.php with placeholders"
echo "  • System returns test OTP code"
echo "  • Use code to test registration flow"
echo "  • ✅ Perfect for development"
echo ""
echo "OPTION B: Test With Real Email (Production)"
echo "  • Configure config.email.php (Step 3 above)"
echo "  • Real emails sent to users"
echo "  • Check inbox for OTP codes"
echo "  • ✅ Production ready"
echo ""

echo -e "${BLUE}📂 FILES TO EDIT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "File: /service/config.email.php"
echo "Lines to change:"
echo "  Line 18: 'username' → your-email@gmail.com"
echo "  Line 19: 'password' → your-app-password"
echo "  Line 23: 'email' → your-email@gmail.com"
echo ""

echo -e "${BLUE}📖 DOCUMENTATION${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• SETUP_EMAIL_ID.md      → Complete guide (Indonesian)"
echo "• SETUP_EMAIL.md         → Complete guide (English)"
echo "• AUTHENTICATION_SYSTEM.md → Technical documentation"
echo "• CSS_STYLING_GUIDE.md    → Design customization"
echo "• README_SYSTEM.md        → System overview"
echo ""

echo -e "${BLUE}🔗 URLS TO ACCESS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Login Form:"
echo "  http://localhost/VSB_project/View/login_register/form_login.php"
echo ""
echo "Registration Form (3-Step OTP):"
echo "  http://localhost/VSB_project/View/login_register/form_register.php"
echo ""

echo -e "${GREEN}✅ PRODUCTION CHECKLIST${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✓${NC} Email configured with real credentials"
echo -e "${GREEN}✓${NC} Test email sending works"
echo -e "${GREEN}✓${NC} Registered users can login"
echo -e "${GREEN}✓${NC} Rate limiting prevents brute force"
echo -e "${GREEN}✓${NC} Database storing hashed passwords"
echo -e "${GREEN}✓${NC} Error messages are helpful"
echo -e "${GREEN}✓${NC} UI/UX looks professional"
echo -e "${GREEN}✓${NC} Works on mobile devices"
echo -e "${GREEN}✓${NC} HTTPS enabled (production)"
echo ""

echo -e "${YELLOW}TROUBLESHOOTING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Q: Email says 'OTP test: 123456'"
echo "A: Email not configured. Fill config.email.php"
echo ""
echo "Q: 'SMTP Error: Could not authenticate'"
echo "A: Check Gmail 2FA enabled and app password correct"
echo ""
echo "Q: Email not in inbox"
echo "A: Check spam folder or wait 3-5 minutes"
echo ""
echo "Q: How to customize colors?"
echo "A: Edit /Design/Css/auth.css - search for #FF2800"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}        Ready to configure? Edit config.email.php!         ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
